// StreetByte Multi-Vendor Directory & Menu Configurations

export const VENDORS = [
  {
    id: 'musa-suya',
    name: "Musa's Charcoal Suya & Grills",
    shortName: "Musa's Suya",
    owner: "Mallam Musa Ibrahim",
    stallNumber: "Stall 4",
    cuisine: "Northern Suya & Skewers",
    tagline: "Authentic Wood-Smoked Suya • Zero Physical Lines",
    rating: 4.9,
    reviewsCount: 382,
    badge: "Grill Master",
    image: "🍢",
    bannerBg: "from-amber-950/70 via-street-card to-street-surface",
    accentColor: "street-orange",
    isOpen: true,
    basePrepTimeMinutes: 10,
    walkingDistanceMinutes: 4,
    bankInfo: {
      bank: "Guaranty Trust Bank (GTB)",
      accountName: "Musa Ibrahim Suya Hub",
      accountNumber: "0123984511"
    },
    categories: [
      { id: 'all', name: 'All Items', icon: 'Flame' },
      { id: 'grills', name: 'Suya & Grills', icon: 'Beef' },
      { id: 'sides', name: 'Sides & Extras', icon: 'Utensils' },
      { id: 'drinks', name: 'Chilled Drinks', icon: 'Coffee' },
      { id: 'combos', name: 'Fast Combos', icon: 'Sparkles' },
    ],
    menuItems: [
      {
        id: 'item-beef-suya',
        vendorId: 'musa-suya',
        name: 'Signature Beef Suya',
        category: 'grills',
        price: 1500,
        description: 'Thinly sliced tender beef skewered & grilled over charcoal with traditional Kano yaji spices.',
        badge: 'Best Seller',
        prepTime: 10,
        inStock: true,
        image: '🥩',
        popularKeywords: ['beef', 'suya', 'beef suya', 'meat'],
        customizable: true,
      },
      {
        id: 'item-chicken-suya',
        vendorId: 'musa-suya',
        name: 'Charcoal Chicken Suya',
        category: 'grills',
        price: 2500,
        description: 'Succulent grilled chicken quarter drumstick thoroughly marinated in spiced yaji pepper.',
        badge: 'Chef Choice',
        prepTime: 12,
        inStock: true,
        image: '🍗',
        popularKeywords: ['chicken', 'chicken suya', 'fowl'],
        customizable: true,
      },
      {
        id: 'item-tozo-suya',
        vendorId: 'musa-suya',
        name: 'Tozo (Special Hump Cuts)',
        category: 'grills',
        price: 2000,
        description: 'Melt-in-your-mouth marbled beef hump cuts, flame-crisped on the outside.',
        badge: 'Popular',
        prepTime: 10,
        inStock: true,
        image: '🥓',
        popularKeywords: ['tozo', 'fat', 'hump'],
        customizable: true,
      },
      {
        id: 'item-kilishi',
        vendorId: 'musa-suya',
        name: 'Gourmet Kilishi Pack',
        category: 'grills',
        price: 1800,
        description: 'Crispy wafer-thin sun-dried beef wafers infused with infused peanut paste and pepper.',
        prepTime: 2,
        inStock: true,
        image: '🥓',
        popularKeywords: ['kilishi', 'dry beef'],
        customizable: false,
      },
      {
        id: 'item-masa',
        vendorId: 'musa-suya',
        name: 'Masa Rice Cakes (4 pcs)',
        category: 'sides',
        price: 600,
        description: 'Fluffy pillow-soft fermented northern rice cakes served with yaji relish.',
        badge: 'Must Try',
        prepTime: 5,
        inStock: true,
        image: '🥞',
        popularKeywords: ['masa', 'rice cake', 'waina'],
        customizable: true,
      },
      {
        id: 'item-corn',
        vendorId: 'musa-suya',
        name: 'Fire-Roasted Sweet Corn',
        category: 'sides',
        price: 500,
        description: 'Fresh cob roasted on open coals, lightly seasoned with salt.',
        prepTime: 5,
        inStock: true,
        image: '🌽',
        popularKeywords: ['corn', 'sweet corn'],
        customizable: false,
      },
      {
        id: 'item-malt',
        vendorId: 'musa-suya',
        name: 'Chilled Can Malt',
        category: 'drinks',
        price: 700,
        description: 'Ice-cold premium Malta beverage, straight from the ice chest.',
        prepTime: 1,
        inStock: true,
        image: '🍺',
        popularKeywords: ['malt', 'malta', 'drink'],
        customizable: false,
      },
      {
        id: 'item-zobo',
        vendorId: 'musa-suya',
        name: 'House Craft Zobo (500ml)',
        category: 'drinks',
        price: 500,
        description: 'Chilled organic hibiscus brew infused with real ginger and cloves.',
        badge: 'Refreshing',
        prepTime: 1,
        inStock: true,
        image: '🍷',
        popularKeywords: ['zobo', 'hibiscus'],
        customizable: false,
      },
      {
        id: 'combo-lunch-rush',
        vendorId: 'musa-suya',
        name: 'The Solo Rush Combo',
        category: 'combos',
        price: 2600,
        description: '1x Beef Suya + 2x Warm Masa Cakes + 1x Ice Chilled Malt. Perfect 15-min lunch fuel!',
        badge: 'Save ₦200',
        prepTime: 8,
        inStock: true,
        image: '⚡',
        popularKeywords: ['solo combo', 'lunch rush', 'suya combo'],
        customizable: true,
      }
    ]
  },
  {
    id: 'mama-blessing',
    name: "Mama Blessing's Jollof & Asun Corner",
    shortName: "Mama Blessing",
    owner: "Madam Blessing Adebayo",
    stallNumber: "Stall 7",
    cuisine: "Smoky Party Jollof & Peppered Meats",
    tagline: "Firewood Party Jollof & Asun • Skip the Buka Line",
    rating: 4.8,
    reviewsCount: 294,
    badge: "Queen of Jollof",
    image: "🍲",
    bannerBg: "from-red-950/70 via-street-card to-street-surface",
    accentColor: "street-red",
    isOpen: true,
    basePrepTimeMinutes: 7,
    walkingDistanceMinutes: 3,
    bankInfo: {
      bank: "Access Bank",
      accountName: "Mama Blessing Canteen Ltd",
      accountNumber: "0812940291"
    },
    categories: [
      { id: 'all', name: 'All Items', icon: 'Flame' },
      { id: 'rice', name: 'Jollof & Rice', icon: 'Utensils' },
      { id: 'meats', name: 'Peppered Meats', icon: 'Beef' },
      { id: 'drinks', name: 'Cold Drinks', icon: 'Coffee' },
      { id: 'combos', name: 'Buka Combos', icon: 'Sparkles' },
    ],
    menuItems: [
      {
        id: 'item-party-jollof',
        vendorId: 'mama-blessing',
        name: 'Smoky Firewood Party Jollof',
        category: 'rice',
        price: 1800,
        description: 'Authentic Nigerian party jollof infused with that distinctive smoky firewood aroma and rich tomato-pepper reduction.',
        badge: 'Top Seller',
        prepTime: 5,
        inStock: true,
        image: '🍚',
        popularKeywords: ['jollof', 'party jollof', 'jollof rice', 'rice'],
        customizable: true,
      },
      {
        id: 'item-fried-rice',
        vendorId: 'mama-blessing',
        name: 'Savory Special Fried Rice',
        category: 'rice',
        price: 2000,
        description: 'Seasoned rice tossed with sweet yellow corn, diced carrots, green peas, and savory liver bites.',
        prepTime: 5,
        inStock: true,
        image: '🍛',
        popularKeywords: ['fried rice', 'rice'],
        customizable: true,
      },
      {
        id: 'item-asun',
        vendorId: 'mama-blessing',
        name: 'Fiery Peppered Goat Asun',
        category: 'meats',
        price: 2500,
        description: 'Wood-smoked diced tender goat meat sizzled with coarse scotch bonnet peppers and sliced onions.',
        badge: 'Extra Spicy 🔥',
        prepTime: 6,
        inStock: true,
        image: '🍖',
        popularKeywords: ['asun', 'goat', 'goat meat', 'peppered goat'],
        customizable: true,
      },
      {
        id: 'item-peppered-turkey',
        vendorId: 'mama-blessing',
        name: 'Crispy Peppered Turkey Wing',
        category: 'meats',
        price: 3000,
        description: 'Huge juicy turkey wing seasoned with local spices, golden fried and bathed in pepper sauce.',
        badge: 'Customer Favorite',
        prepTime: 6,
        inStock: true,
        image: '🍗',
        popularKeywords: ['turkey', 'peppered turkey', 'turkey wing'],
        customizable: true,
      },
      {
        id: 'item-dodo',
        vendorId: 'mama-blessing',
        name: 'Golden Fried Dodo (Plantain)',
        category: 'rice',
        price: 700,
        description: 'Sweet, caramelized ripe plantain cubes fried to golden brown perfection.',
        badge: 'Add-On Star',
        prepTime: 3,
        inStock: true,
        image: '🍌',
        popularKeywords: ['dodo', 'plantain', 'fried plantain'],
        customizable: false,
      },
      {
        id: 'item-chapman',
        vendorId: 'mama-blessing',
        name: 'Classic Nigerian Chapman (500ml)',
        category: 'drinks',
        price: 1000,
        description: 'Chilled signature drink with fruity zest, angostura bitters, fresh lime, and cucumber slice.',
        badge: 'House Special',
        prepTime: 2,
        inStock: true,
        image: '🍹',
        popularKeywords: ['chapman', 'cocktail', 'mocktail', 'drink'],
        customizable: false,
      },
      {
        id: 'item-coke',
        vendorId: 'mama-blessing',
        name: 'Chilled Coca-Cola (50cl)',
        category: 'drinks',
        price: 400,
        description: 'Ice-cold original Coca-Cola glass bottle.',
        prepTime: 1,
        inStock: true,
        image: '🥤',
        popularKeywords: ['coke', 'coca cola', 'soda'],
        customizable: false,
      },
      {
        id: 'combo-buka-king',
        vendorId: 'mama-blessing',
        name: 'The Buka Executive Box',
        category: 'combos',
        price: 4800,
        description: 'Party Jollof Rice + Crispy Dodo + Golden Peppered Turkey Wing + Chilled Chapman. Save ₦500!',
        badge: 'Ultimate Feast',
        prepTime: 8,
        inStock: true,
        image: '🍱',
        popularKeywords: ['executive box', 'jollof combo', 'turkey pack'],
        customizable: true,
      },
      {
        id: 'combo-asun-bowl',
        vendorId: 'mama-blessing',
        name: 'Asun & Jollof Quick Bowl',
        category: 'combos',
        price: 3300,
        description: 'Generous bowl of Smoky Jollof topped with Spicy Peppered Asun and Golden Dodo. Rush favorite!',
        badge: 'Save ₦300',
        prepTime: 6,
        inStock: true,
        image: '🍲',
        popularKeywords: ['asun bowl', 'quick bowl', 'asun rice'],
        customizable: true,
      }
    ]
  }
];

export const CUSTOMIZATION_OPTIONS = {
  spiceLevels: [
    { id: 'mild', label: 'Mild Spice (Flavorful, Gentle)', extra: 0 },
    { id: 'medium', label: 'Medium (Standard Street Heat)', extra: 0 },
    { id: 'fire', label: 'Fire! (Extra Hot Scotch Bonnet / Yaji 🔥)', extra: 0 },
  ],
  onions: [
    { id: 'standard', label: 'Fresh Sliced Onions Included' },
    { id: 'side', label: 'Onions on the Side' },
    { id: 'none', label: 'No Onions' },
  ],
  packaging: [
    { id: 'foil', label: 'Foil / Heat Container (Stays hot 30+ mins)' },
    { id: 'paper', label: 'Classic Street Takeaway Pack' },
  ]
};

export const MOCK_ORDERS = [
  {
    id: 'SB-101',
    vendorId: 'musa-suya',
    vendorName: "Musa's Charcoal Suya & Grills",
    stallNumber: 'Stall 4',
    customerName: 'Chidi O.',
    customerPhone: '0803***491',
    items: [
      { name: 'Signature Beef Suya', quantity: 2, spice: 'fire', onions: 'side', price: 1500 },
      { name: 'Chilled Can Malt', quantity: 2, price: 700 }
    ],
    total: 4400,
    status: 'ready',
    placedAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    prepTimeMinutes: 10,
    paymentStatus: 'PAID_VERIFIED',
    paymentRef: 'TRX-829104',
    etaMinutesRemaining: 0,
  },
  {
    id: 'SB-102',
    vendorId: 'mama-blessing',
    vendorName: "Mama Blessing's Jollof & Asun Corner",
    stallNumber: 'Stall 7',
    customerName: 'Amina Bello',
    customerPhone: '0812***820',
    items: [
      { name: 'Smoky Firewood Party Jollof', quantity: 1, spice: 'medium', onions: 'standard', price: 1800 },
      { name: 'Golden Fried Dodo (Plantain)', quantity: 1, price: 700 },
      { name: 'Classic Nigerian Chapman (500ml)', quantity: 1, price: 1000 }
    ],
    total: 3600,
    status: 'preparing',
    placedAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    prepTimeMinutes: 8,
    paymentStatus: 'PAID_VERIFIED',
    paymentRef: 'TRX-948123',
    etaMinutesRemaining: 3,
  },
  {
    id: 'SB-103',
    vendorId: 'musa-suya',
    vendorName: "Musa's Charcoal Suya & Grills",
    stallNumber: 'Stall 4',
    customerName: 'Tunde Bakare',
    customerPhone: '0901***112',
    items: [
      { name: 'The Solo Rush Combo', quantity: 1, spice: 'fire', onions: 'standard', price: 2600 }
    ],
    total: 2600,
    status: 'incoming',
    placedAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    prepTimeMinutes: 8,
    paymentStatus: 'PAID_VERIFIED',
    paymentRef: 'TRX-103984',
    etaMinutesRemaining: 8,
  }
];

export function getVendorById(id) {
  return VENDORS.find(v => v.id === id) || VENDORS[0];
}

export function getAllMenuItems() {
  return VENDORS.flatMap(v => v.menuItems);
}
